# Generated by Django 3.0.4 on 2020-03-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('cedula', models.CharField(max_length=60)),
                ('rol', models.CharField(max_length=60)),
                ('actividad_reciente', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
