# Generated by Django 2.2.6 on 2020-03-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rolesusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolesUsuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Usuario'), ('3', 'Operador')], max_length=1),
        ),
    ]
