# Generated by Django 2.2.6 on 2020-03-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='ID_Empaque',
            new_name='Empaque',
        ),
        migrations.RenameField(
            model_name='incidencia',
            old_name='ID_Producto',
            new_name='Producto',
        ),
        migrations.RenameField(
            model_name='incidencia',
            old_name='ID_Usuario',
            new_name='Usuario',
        ),
    ]
